/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AgentMemoryBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "AgentPluginsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "AgentRecordingsBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "AgentRuntime": {
      "name": string
      "qualifier": string
      "type": "sst.aws.Workflow"
    }
    "Api": {
      "type": "sst.aws.ApiGatewayV1"
      "url": string
    }
    "ApiFunction": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AuditBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "AuditQueue": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "AuditWriter": {
      "name": string
      "type": "sst.aws.Function"
    }
    "AuthIssuer": {
      "name": string
      "type": "sst.aws.Function"
    }
    "EventBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "ProcedureRecorder": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ProcedureScheduler": {
      "name": string
      "type": "sst.aws.Function"
    }
    "Table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "ToolBrowser": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ToolCalendar": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ToolGmail": {
      "name": string
      "type": "sst.aws.Function"
    }
    "ToolHttpFetch": {
      "name": string
      "type": "sst.aws.Function"
    }
  }
}

import "sst"
export {}