/**
 * Selector hardening — shared between the recorder (which computes ranked candidates as the user
 * clicks) and replay (which tries each candidate in order, first match wins). The recorder script
 * itself (services/procedure-recorder/src/recorder-script.ts) runs in the page and can't import
 * this module, so it carries its own copy of `looksAutoGenerated`; keep the two in sync.
 */

/** Replay stores at most this many candidates per step. */
export const SELECTOR_CANDIDATE_LIMIT = 3;

/**
 * True when an `id` is almost certainly framework-minted (React `useId`, styled-components,
 * Emotion, CSS-modules hashes, Angular `_ngcontent`) and therefore unstable across renders — such
 * ids must not be used as a selector.
 */
export function looksAutoGenerated(id: string): boolean {
  if (!id) return true;
  if (/^[0-9]+$/.test(id)) return true; // digits only
  if (/^:r[0-9a-z]+:?$/i.test(id)) return true; // React 18 useId, e.g. ":r3:"
  if (/[0-9a-f]{6,}/i.test(id) && !/[-_]/.test(id)) return true; // long hex-ish blob, no word separators
  if (/^(mui-|radix-|headlessui-|ember|ng-|sc-|css-)[0-9a-z-]{3,}$/i.test(id)) return true;
  if (id.length > 40) return true;
  return false;
}

/** Dedupe (stable) and cap to `SELECTOR_CANDIDATE_LIMIT`. */
export function rankSelectors(candidates: readonly string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const c of candidates) {
    const t = c.trim();
    if (!t || seen.has(t)) continue;
    seen.add(t);
    out.push(t);
    if (out.length >= SELECTOR_CANDIDATE_LIMIT) break;
  }
  return out;
}
